"""HTML report generator - dark theme, card-based layout - AI 趋势监控精简版（带简评）"""

from datetime import datetime
from zoneinfo import ZoneInfo


def generate_html_report(product_hunt_data, ai_tools_data, github_trending_data, hackernews_data, ai_news_data=None, comments=None):
    """
    Generate a responsive dark-theme HTML report from all data sources.
    """
    if comments is None:
        comments = {}

    cst = ZoneInfo("Asia/Shanghai")
    now = datetime.now(cst)
    date_str = now.strftime("%Y-%m-%d %H:%M (北京时间)")

    css = """
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; }
        .header { background: linear-gradient(135deg, #161b22 0%, #0d1117 100%); border-bottom: 1px solid #21262d; padding: 32px 24px; text-align: center; }
        .header h1 { font-size: 2.2em; color: #58a6ff; margin-bottom: 8px; }
        .header .date { color: #8b949e; font-size: 0.95em; }
        .nav { background: #161b22; padding: 12px 24px; display: flex; gap: 16px; justify-content: center; border-bottom: 1px solid #21262d; }
        .nav a { color: #58a6ff; text-decoration: none; padding: 6px 12px; border-radius: 6px; }
        .nav a:hover { background: #21262d; }
        .container { max-width: 1100px; margin: 0 auto; padding: 24px; }
        .section { margin-bottom: 40px; }
        .section h2 { color: #58a6ff; font-size: 1.5em; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 1px solid #21262d; }
        .section .comment { background: #1c2333; border-left: 3px solid #58a6ff; padding: 10px 14px; margin-bottom: 16px; border-radius: 0 6px 6px 0; color: #a8d4ff; font-size: 0.95em; line-height: 1.5; }
        .section .comment::before { content: "💡 "; }
        .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 16px; }
        .card { background: #161b22; border: 1px solid #21262d; border-radius: 8px; padding: 16px; transition: border-color 0.2s; }
        .card:hover { border-color: #58a6ff; }
        .card h3 { font-size: 1.05em; margin-bottom: 8px; }
        .card h3 a { color: #79c0ff; text-decoration: none; }
        .card h3 a:hover { text-decoration: underline; }
        .card p { color: #8b949e; font-size: 0.9em; margin: 4px 0; }
        .card .meta { color: #6e7681; font-size: 0.85em; }
        .card .stars { color: #f0b90b; }
        .footer { text-align: center; padding: 24px; color: #6e7681; font-size: 0.85em; border-top: 1px solid #21262d; }
        @media (max-width: 768px) { .grid { grid-template-columns: 1fr; } .header h1 { font-size: 1.5em; } }
    """

    sections_html = []

    # GitHub Trending
    sections_html.append(_render_section("🐙 GitHub Trending", "github", github_trending_data, _render_github_card, comments.get("github", "")))

    # Product Hunt
    sections_html.append(_render_section("🚀 Product Hunt 今日热门", "producthunt", product_hunt_data, _render_product_card, comments.get("product_hunt", "")))

    # AI Tools
    sections_html.append(_render_section("🧰 AI 工具推荐", "aitools", ai_tools_data, _render_aitool_card, comments.get("ai_tools", "")))

    # Hacker News
    sections_html.append(_render_section("💬 Hacker News 热议", "hackernews", hackernews_data, _render_hn_card, comments.get("hacker_news", "")))

    # AI News
    if ai_news_data:
        sections_html.append(_render_section("📈 AI 行业新闻（投资参考）", "ainews", ai_news_data, _render_news_card, comments.get("ai_news", "")))

    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI 趋势日报</title>
    <style>{css}</style>
</head>
<body>
<div class="header">
    <h1>🤖 AI 趋势日报</h1>
    <p class="date">{date_str}</p>
</div>
<div class="nav">
    <a href="opportunity.html">🚀 创业机会分析</a>
    <a href="#github">GitHub</a>
    <a href="#producthunt">Product Hunt</a>
    <a href="#aitools">AI 工具</a>
    <a href="#hackernews">Hacker News</a>
</div>
<div class="container">
{''.join(sections_html)}
</div>
<div class="footer">Generated by <a href="https://github.com/fsmhuc/trend-monitor" style="color:#58a6ff">trend-monitor</a></div>
</body>
</html>"""


def _render_section(title, anchor, data, card_fn, comment=""):
    """渲染一个板块，可选带简评"""
    comment_html = f'<div class="comment">{comment}</div>' if comment else ""
    if not data:
        return f"""<div class="section" id="{anchor}"><h2>{title}</h2>{comment_html}<p style="color:#6e7681">暂无数据</p></div>"""
    cards = "".join(card_fn(item) for item in data)
    return f"""<div class="section" id="{anchor}"><h2>{title}</h2>{comment_html}<div class="grid">{cards}</div></div>"""


def _render_github_card(item):
    name = item.get("name", "未知")
    desc = item.get("description", "无描述")
    stars = item.get("stars", "N/A")
    link = f"https://github.com/{name}"
    return f"""<div class="card"><h3><a href="{link}" target="_blank">{name}</a></h3><p>{desc}</p><p class="stars">⭐ {stars}</p></div>"""


def _render_product_card(item):
    name = item.get("name", "未知")
    tagline = item.get("tagline", "无简介")
    link = item.get("link", "")
    return f"""<div class="card"><h3><a href="{link}" target="_blank">{name}</a></h3><p>{tagline}</p></div>"""


def _render_aitool_card(item):
    name = item.get("name", "未知")
    desc = item.get("description", "无描述")
    link = item.get("link", "")
    category = item.get("category", "")
    meta = f"分类: {category}" if category else ""
    return f"""<div class="card"><h3><a href="{link}" target="_blank">{name}</a></h3><p>{desc}</p>{f'<p class="meta">{meta}</p>' if meta else ''}</div>"""


def _render_hn_card(item):
    title = item.get("title", "未知")
    url = item.get("link", "")
    points = item.get("points", "N/A")
    comments = item.get("comments", "N/A")
    return f"""<div class="card"><h3><a href="{url}" target="_blank">{title}</a></h3><p class="meta">得分: {points} · 评论: {comments}</p></div>"""


def _render_news_card(item):
    title = item.get("title", "未知")
    link = item.get("link", "")
    source = item.get("source", "")
    desc = item.get("desc", "")
    return f"""<div class="card"><h3><a href="{link}" target="_blank">{title}</a></h3><p class="meta">来源: {source}</p>{f'<p>{desc[:150]}</p>' if desc else ''}</div>"""
